### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by hexarotor6** [MOV-AI/containers-spawner-base#36]
trying to run the README command but i get the following output.

~/containers-spawner-base$     docker build --pull -t spawner-noetic -f docker/noetic/Dockerfile --target spawner .
Sending build context to Docker daemon  284.7kB
Step 1/25 : ARG DOCKER_REGISTRY="registry.aws.cloud.mov.ai"
Step 2/25 : FROM ${DOCKER_REGISTRY}/devops/movai-base-noetic:v1.4.9 AS spawner
Head "https://registry.aws.cloud.mov.ai/v2/devops/movai-base-noetic/manifests/v1.4.9": no basic auth credentials

**Comment by AlexFernandes-MOVAI** [comment]
good point here, the base image is not referenced by its public name

**Comment by xsoulp** [comment]
meanwhile i suggest this section is added to the README.md:


## Dependencies

This image depends on `movai-base` docker image - https://github.com/MOV-AI/containers-movai-base

## Alternative build
If you have built `movai-base` locally already, you can build `spawner` images using that source by:
1) Changing the Dockerfile `FROM` entry.
2) Removing `--pull` argument 

Example: building spawner-noetic
1) Open file `docker/noetic/Dockerfile`
2) Replace line `FROM ${DOCKER_REGISTRY}/devops/movai-base-noetic:v1.4.9 AS spawner` by `FROM "movai-base:noetic" AS spawner`
3) Call `docker build -t spawner-noetic -f docker/noetic/Dockerfile --target spawner .`

**Comment by AlexFernandes-MOVAI** [comment]
Tested OK on codespace
